[package]
name = "brainchuck"
version = "0.1.0"
authors = ["Matias Fontanini <matias.fontanini@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "^1.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", rev = "41857f9", features = ["llvm11-0"] }
structopt = "^0.3"
